const wineries = [
    { name:"Bodegas Eguren", badge:"D.O.Ca. Rioja", desc:"Bodega familiar de quinta generación en el corazón de La Rioja Alta. Viñedos de más de 80 años.", meta:["Premium","Fundada 1870","Familiar"], certs:["eco","tur"], color:"linear-gradient(135deg,#9a7a50,#5a3a20)" },
    { name:"Viñedos del Contino", badge:"D.O.Ca. Rioja", desc:"Finca de viñedo único en la margen derecha del Ebro. Pioneros en el concepto de 'château' en España.", meta:["Viñedo único","1969"], certs:["eco"], color:"linear-gradient(135deg,#7a5a40,#3a2010)" },
    { name:"Finca Allende", badge:"D.O.Ca. Rioja", desc:"Nuevo productor de referencia. Vinificaciones de parcela única en Briones con cepas viejas de Tempranillo.", meta:["Nuevo productor","Parcela única"], certs:["bio","eco"], color:"linear-gradient(135deg,#4a7c59,#2a4a39)" },
    { name:"Bodegas Pesquera", badge:"D.O. Ribera del Duero", desc:"Alejandro Fernández revolucionó Ribera del Duero en los años 80. Hoy sigue siendo referencia absoluta.", meta:["Premium","Fundada 1972"], certs:["tur"], color:"linear-gradient(135deg,#8a4a40,#4a1a10)" },
    { name:"Pazo Señoráns", badge:"D.O. Rías Baixas", desc:"Palacio del siglo XVI rodeado de viñedos de Albariño junto a la ría. Colección de añadas antiguas única en España.", meta:["Premium","S. XVI","Biodinámica"], certs:["eco","bio","tur"], color:"linear-gradient(135deg,#5a7a6a,#2a4a3a)" },
    { name:"Bodegas Mustiguillo", badge:"D.O. Utiel-Requena", desc:"Rescate de la uva Bobal en viñedos centenarios en la meseta valenciana. Producción limitada y artesanal.", meta:["Producción limitada","Bobal"], certs:["eco"], color:"linear-gradient(135deg,#7a6a4a,#4a4a2a)" },
    { name:"Bodegas Toro Albalá", badge:"D.O. Montilla-Moriles", desc:"Enclavada en una antigua planta eléctrica del siglo XX. Sus Pedro Ximénez de añadas históricas son únicos.", meta:["Edificio histórico","Pedro Ximénez"], certs:["tur"], color:"linear-gradient(135deg,#8a7a3a,#5a4a1a)" },
    { name:"Casa Castillo", badge:"D.O. Jumilla", desc:"Referencia de Jumilla con la variedad Monastrell. Viñedos de más de 50 años en suelo arenoso.", meta:["Monastrell","50+ años cepa"], certs:["eco","tur"], color:"linear-gradient(135deg,#6a4a5a,#3a1a2a)" },
    { name:"Celler Can Ràfols dels Caus", badge:"D.O. Penedès", desc:"Bodega pionera en viticultura ecológica en Cataluña. Variedades autóctonas y experimentos únicos desde 1979.", meta:["Premium","Ecológica pionera"], certs:["eco","bio","tur"], color:"linear-gradient(135deg,#5a6a4a,#2a3a1a)" },
    { name:"Viñas Altas", badge:"D.O. Ribera del Guadiana", desc:"Pequeño productor de Extremadura apostando por variedades locales en suelos de granito. Producción artesanal.", meta:["Nuevo productor","Artesanal"], certs:["eco"], color:"linear-gradient(135deg,#7a5a4a,#4a3a2a)" },
    { name:"Costers del Segre", badge:"D.O. Costers del Segre", desc:"Bodegas de altura en el Pirineo leridano. Viñedo de montaña con gran amplitud térmica.", meta:["Viñedo montaña","Altura"], certs:["eco","tur"], color:"linear-gradient(135deg,#4a5a6a,#1a2a3a)" }
  ];
